python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 1.25 --seed 6404 --minMTBF 50 --maxMTBF 70
python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 1.39 --seed 6404 --minMTBF 50 --maxMTBF 70
python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 1.5625 --seed 6404 --minMTBF 50 --maxMTBF 70
python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 1.7857 --seed 6404 --minMTBF 50 --maxMTBF 70
python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 2.5 --seed 6404 --minMTBF 50 --maxMTBF 70
python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 4.17 --seed 6404 --minMTBF 50 --maxMTBF 70
#python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 0.6 --seed 5063 --minMTBF 50 --maxMTBF 70
#python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 1.0 --seed 8914 --minMTBF 50 --maxMTBF 70
#python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 1.4 --seed 1468 --minMTBF 50 --maxMTBF 70
#python env/utils/benchmark_generator.py --baseFile $1 --baseFilePath datasets/base_files/$1.fjs --c 2.4 --seed 7638 --minMTBF 50 --maxMTBF 70
